"""Initial revision 6

Revision ID: 0530efa9e326
Revises: c7b23e9a86e1
Create Date: 2026-04-09 17:08:12.146787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0530efa9e326'
down_revision: Union[str, None] = 'c7b23e9a86e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('max_clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'max_clicks')
    # ### end Alembic commands ###
