"""Initial revision 2

Revision ID: ac5aa99efd44
Revises: 3703dd13c4d0
Create Date: 2026-04-08 14:36:56.029016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5aa99efd44'
down_revision: Union[str, None] = '3703dd13c4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_short_code', table_name='links')
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.create_index('ix_links_short_code', 'links', ['short_code'], unique=False)
    # ### end Alembic commands ###
