"""Initial revision 3

Revision ID: c7b23e9a86e1
Revises: ac5aa99efd44
Create Date: 2026-04-09 15:05:02.414140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b23e9a86e1'
down_revision: Union[str, None] = 'ac5aa99efd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'expires_at')
    # ### end Alembic commands ###
